name: auth
services:
  app:
    build:
      context: ./app
    image: node-app
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-net

  mongodb:
    image: mongo:8.0
    restart: always
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./mongo.env
    healthcheck:
      test: ["CMD-SHELL",'mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "db.stats().ok" --quiet']
      interval: 1m
      retries: 3
      timeout: 30s
      start_interval: 15s
    networks:
      - app-net

networks:
  app-net:
volumes:
  mongo-data:
